language: scala
scala:
    - "2.10.3"
jdk:
    - openjdk7
    - openjdk6
git:
    submodules: false
# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
