package adept.sbt

import sbt._
import adept.lockfile.Lockfile
import scala.concurrent.duration.FiniteDuration
import scala.util.matching.Regex
import java.net.URL

object AdeptKeys {
  val adeptTimeout = settingKey[Int]("Adepts timeout (in minutes) for downloading artifacts")
  val adeptDirectory = settingKey[File]("Adepts home directory. Defaults to: ~/.adept")
  val adeptImportsDirectory = settingKey[File]("Adepts imports directory. Defaults to: project/adept/imports")
  val adeptClasspath = taskKey[Seq[Attributed[File]]]("Classpath generated by adept")
  val adeptLockfileGetter = settingKey[String => File]("Get Adepts lockfile for this configuration")
  val adeptLockfiles = taskKey[Map[String, File]]("Adepts lockfiles")
  val adeptLockfileContent = taskKey[Lockfile]("The contents of Adepts lockfile")
  val adepthubUrl = settingKey[String]("Url used for AdeptHub (used for searching and contributions)")
}