package adept.sbt

import adept.lockfile.Lockfile
import sbt._

object AdeptKeys {
  val adeptTimeout = settingKey[Int]("Adept's timeout (in minutes) for downloading artifacts")
  val adeptDirectory = settingKey[File]("Adept's home directory. Defaults to: ~/.adept")
  val adeptImportsDirectory = settingKey[File](
    "Adept's imports directory. Defaults to: project/adept/imports")
  val adeptClasspath = taskKey[Seq[Attributed[File]]]("Classpath generated by adept")
  val adeptLockfileGetter = settingKey[String => File]("Get Adept's lockfile for this configuration")
  val adeptLockfiles = taskKey[Map[String, File]]("Adept's lockfiles")
  val adeptLockfileContent = taskKey[Lockfile]("The contents of Adept's lockfile")
  val adepthubUrl = settingKey[String]("URL used for AdeptHub (used for searching and contributions)")
}
